version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/

  neo4j:
    image: neo4j:5.19
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - .env
    volumes:
      - neo4j_data:/data
      - neo4j_conf:/conf
    restart: always

  chromadb:
    image: chromadb/chroma:latest
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./chroma:/chroma/chroma


volumes:
  postgres_data:
  neo4j_data:
  neo4j_conf:

