version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ndsds
      POSTGRES_PASSWORD: sd3qd32
      POSTGRES_DB: mydatabase
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
